---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cc.
--- DateTime: 2024/12/23 14:17
---

-- 参数列表
local seckillVoucherID = ARGV[1]
local userID = ARGV[2]

-- key列表
local stockKey = 'seckill:stock:'..seckillVoucherID
local orderKey = 'seckill:order:'..seckillVoucherID

-- 1. 查看秒杀券库存是否充足
if tonumber(redis.call('get', stockKey)) <= 0 then
    -- 秒杀券不足则返回1
    return 1
end

-- 2. 判断一人一单
if redis.call('sismember', orderKey, userID) == 1 then
    --此人已经下过单
    return 2
end

-- 3. 减库存并且创建订单
redis.call('incrby',stockKey, -1)
redis.call('sadd',orderKey, userID)
return 0
